### ISSUE TITLE
Provide failsafe against unavailable props

### ISSUE THREAD

**Issue by robbevp** [accentor/web#117]
If a related property is not available, the app tends to freeze or components will not show up.
This already happens when an object is destroyed but is still refered to on another object (see #77 ), or might happen when loading objects is stuck (for example, due to a network error, see #65).

Once we have #75 merged, this will only become more common, since we won't know the order in which objects are added to the store.

## Proposed changes
* [x] provide a fallback in components (`TrackGenres`, `TrackArtists` and `AlbumArtists`) so that they get displayed even if some of the related objects are missing.
* [x] provide a fallback in getters (most notably `Tracks/tracksByAlbumAndNumber` where most of the critical errors seem to occur) so that it will always output something

**Comment by charvp** [comment]
This happened when testing #44 and disabled updates for the flagged track count. An album wasn't found.
