### ISSUE TITLE
Add interval for rescan if rescan is currently running

### ISSUE THREAD

**Issue by robbevp** [accentor/web#138]
If a user loads or reloads the data and a rescan is running, the state of the rescan should be set to running and the info should be fetched on the same interval as for the user that triggered it.

**Comment by charvp** [comment]
This is the current behaviour?

**Comment by robbevp** [comment]
No, if you currently load the application or reload the data and another user or browser triggered the rescan, you get a snapshot of the scanner but it isn't updated.
Also the button to start a scan is not disabled and the client will not know when to fetch the new data
