### ISSUE TITLE
Figure out and fix memory leak

### ISSUE THREAD

**Issue by charvp** [accentor/web#148]
Not necessarily introduced by #44, but it certainly exacerbated the issue. Before base memory usage (on the settings page) was ~80MiB, now it is around ~800MiB.

**Comment by robbevp** [comment]
The biggest difference that #44 introduced after loading is the presence of a loaded prop on each object. Though an extra prop on ±60.000 object make a difference, it shouldn't make this big of a difference.

Have you noticed any pages/components that seems to have more problems? Maybe the computed properties introduced by #144 have some part in this?

**Comment by robbevp** [comment]
This seemed to be caused by the new way of commiting. 
The current develop branch, but with the following `setTracks` commit, leaves us with ±900MB of memory. This jumps from around ±90MB when the commit happens
```
    setTracks(state, payload) {
      let newTracks = { ...state.tracks };
      state.tracks = {};
      for (let track of payload) {
        newTracks[track.id] = track;
      }
      state.tracks = newTracks;
      newTracks = {};
    },
```
