### ISSUE TITLE
Make album and artist cards have all the same height

### ISSUE THREAD

**Issue by charvp** [accentor/web#19]

**Comment by robbevp** [comment]
I made a quick example of the albumCard with a fixed height.
<img width="900" alt="Screenshot 2020-03-26 at 17 39 04" src="https://user-images.githubusercontent.com/48474670/77679967-9346fc80-6f93-11ea-9f39-0271ad0b807b.png">

Some choices to make about this:
* How many lines of text do we want before we cut of?
* Do we want to show the full title/albumartist on hover for all cards or only if the text is truncated?
* Do we show the full content by temporarily expanding the card or with a tooltip/popover?

**Comment by charvp** [comment]
I prefer one line before cutoff (the way lines are split also looks pretty bad right now, because words are just split arbitrarily). I would do a simple browser-level tooltip for all text that _can_ be truncated on a card.
