### ISSUE TITLE
Newly created artists aren't added in the right order on mass edit

### ISSUE THREAD

**Issue by charvp** [accentor/web#34]

**Comment by robbevp** [comment]
@charvp shouldn't we allow the user to determine the order of the added artists? If no order is given the artists is added last.

**Comment by charvp** [comment]
This is something you reported on gitlab: https://gitlab.com/accentor/web/-/issues/53

**Comment by charvp** [comment]
Letting people choose where the new artists get added seems like it's not a 1.0 feature to me. But the bug you reported is very much a 1.0 bug.
