### ISSUE TITLE
On this day doesn't change when day changes

### ISSUE THREAD

**Issue by charvp** [accentor/web#37]

**Comment by robbevp** [comment]
There doesn't seem to be a clean solution for this.
To change this, we would need to trigger an update of the getter. So we would need to trigger some kind of commit when the date changes that updates `state.albums`. I don't think we want to manipulate the store in such a way.
One workaround way to do this would be to force `loadData` when the date changes.

**Comment by charvp** [comment]
I was thinking about this recently. I think the cleanest solution is to have a `currentDay` property at the root of the store. This can be updated by an [interval](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval) in the `App.vue` file. Similar to here: https://vuejsexamples.com/simple-countdown-timer-vue-component/.

Instead of using Date in the current day view, you can use this property. When the interval updates the property, the view should then update as well.

**Comment by charvp** [comment]
We will need something similar if we want to do automatic refreshing of the data at some point, I think.
