### ISSUE TITLE
Scroll position does not reset on navigate

### ISSUE THREAD

**Issue by robbevp** [accentor/web#549]
##### Reproduction steps

  1. Go to page that scrolls (fe. artists with a lot of albums or homepage). 
  2. Scroll down a bit
  3. Click on element to navigate
  4. Notice how scroll position is at the same place as before

(This is obvs more noticable on smaller resolution screens or small viewports)

##### Expected behaviour
After navigating from one page to the next, a user should start at the top of the page again.

##### System information
Chome 91 on macOS 11.4

(This might be an issue with vuetify, or might have been there all along and I only just noticed it now)

**Comment by chvp** [comment]
I'm pretty sure this has been the case since forever.
