### ISSUE TITLE
Add recently listened albums/artists to homepage

### ISSUE THREAD

**Issue by chvp** [accentor/web#645]
I usually listen to the same album multiple times in short time periods or (re-)discover an artist and want to listen to them a lot. Adding this would make those albums/artists more discoverable. This sort of overlaps with the idea of dynamic playlists/collages, but until we have those it makes sense to add this IMO.

**Comment by robbevp** [comment]
I like this idea, but to remarks:
* What constitutes a played album/artist? Is that just that one song from that artist/album was played?
* In the long run, we might want to allow the user to select which elements to show on the homepage - I notice there are things I hardly ever use (random artist) and things I use a lot

**Comment by chvp** [comment]
> I like this idea, but to remarks:
> 
> * What constitutes a played album/artist? Is that just that one song from that artist/album was played?

This is what I had in mind, yes.

> * In the long run, we might want to allow the user to select which elements to show on the homepage - I notice there are things I hardly ever use (random artist) and things I use a lot

Sure, but that's definitely a "later" kind of idea, I think.
