### ISSUE TITLE
Log unexpected errors to the console

### ISSUE THREAD

**Issue by robbevp** [accentor/web#962]
Every once in a while, an error will occur that does not align with the format we expect in our `Errors.vue` component.

This results in an unclear or empty error message being shown to the user. Their source is often hard to debug, since its tricky to inspect the state of the store in production at runtime.

We might be better of if we log these in the console, using `console.error` instead of showing an empty error message (or in addition to showing the empty error message).

@chvp what do you think?

**Comment by chvp** [comment]
Sure, makes sense. We could also just log every error, since we throw some info away when showing it in the UI (which a developer might want to use).
